### ISSUE TITLE
System requirements clarification

### ISSUE THREAD

**Issue by rokbra** [bragagnololu/UNet-defmapping#2]
Hi,

I recently tried out awesome UNET-defmapping with mostly up to date packages (see below), however with no luck. I wonder maybe a little clarification on originally used package names and versions would solve all the issues I encountered tinkering around and trying to make this amazing code to work in my environment.

  Python 3.7.10
? Keras 2.4.3
? Tensorflow 2.3.0
? sklearn: scikit-learn 0.24.2
  rasterio 1.1.5
? rkimage ?
  fiona 1.8.9.post2
? cv2: opencv-python
  numpy-indexed 0.3.5
  sentinelsat 1.0.0
  zipfile.py
? glob2 0.7
  matplotlib 3.4.2

I'd be very grateful for any kind of assistance.

**Comment by bragagnololu** [comment]
Hi,

Here are the versions of the libraries used in the development of the algorithm:

keras-base=2.3.1
keras-gpu=2.3.1
tensorflow=2.1.0
tensorflow-base=2.1.0
tensorflow-gpu=2.1.0
scikit-learn=0.22.2.post1
rasterio=1.1.3
fiona=1.8.13
opencv=4.2.0
numpy=1.18.1
numpy-indexed
sentinelhub=3.0.2
sentinelsat=0.13

zipfile.py: https://github.com/python/cpython/blob/3.9/Lib/zipfile.py / https://docs.python.org/3/library/zipfile.html

Let me know if any problem occur!

**Comment by rokbra** [comment]
I highly appreciate your quick response. I tested the algorithm on new environment with described libraries and came to conclusion that I simply lacked a proper GPU... And so I tested it out on another machine, and even with up to date libraries everything worked perfectly after some tinkering:
model_UNET_def.py
line 58:     model = tf.keras.Model(inputs = inputs, outputs = conv10)
and [increase of swap memory](https://askubuntu.com/questions/178712/how-to-increase-swap-space) (linux) from 2GB to ~10GB - because kernel kept crashing due to [numpy zeros function](https://stackoverflow.com/questions/27574881/why-does-numpy-zeros-takes-up-little-space)

Thank you and I hope you will get the best possible evaluations for such amazing work. :)
