### ISSUE TITLE
Geojson file does not exist

### ISSUE THREAD

**Issue by amirjalilifard** [bragagnololu/UNet-defmapping#3]
Dear Lucimara,

I am trying to download the images but it seems that the **rondonia_square3.geojson** does not exist. Could you please inform me where can I find this file so that I can run the codes?

I am looking forward to your answer

Best regards

**Comment by bragagnololu** [comment]
Dear Amir,

Indeed, the file was missing. I've just added it in the ['Files'](https://github.com/bragagnololu/UNet-defmapping/tree/master/Files) folder.

I hope you can run the codes now.

Best regards

**Comment by amirjalilifard** [comment]
Now, the downloading part is working! Thank you very much!
